version: "3.8"
services:
  apigateway:
    container_name: apigateway
    build:
      context: ./ApiGateway
      dockerfile: Dockerfile
    ports:
      - 8004:8000
  usermicroservice:
    container_name: usermicroservice
    build:
      context: ./User
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - 8001:8000
    environment:
      - MYSQL_ADDR=mysql
  mysql:
    container_name: mysql
    build:
      context: ./User/mysqlfiles
      dockerfile: Dockerfile
    environment:
      MYSQL_PASSWORD: password
      MYSQL_USER: root
    image: mysql:5.7.20
    ports:
      - 0.0.0.0:7703:3306